ALTER TABLE contracts RENAME COLUMN amount TO init_fund;

ALTER TABLE contracts ADD COLUMN IF NOT EXISTS snap_balance TEXT NOT NULL DEFAULT '0';
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS available_fund TEXT NOT NULL DEFAULT '0';
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS used_fund TEXT NOT NULL DEFAULT '0';
