// DTOs (Data Transfer Objects)
use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
pub struct ChallengeQuery {
    /// The Ethereum wallet address (e.g., 0x...)
    pub wallet_address: String,
}

#[derive(Serialize, Deserialize)]
pub struct ChallengeResponse {
    /// The unique nonce the user must sign
    pub nonce: String,
}

#[derive(Deserialize, Serialize)]
pub struct VerifySignaturRequest {
    pub msg: String,
    /// The signature generated by signing the nonce
    pub signature: String,
}

#[derive(Serialize, Deserialize)]
pub struct SessionResponse {
    /// JWT Bearer Token for authenticated requests
    pub token: String,
}
