[package]
name = "trade-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy.workspace = true
log.workspace = true
kucoin.workspace =true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
share = { path = "../../lib/share" }
sqlx.workspace = true
tokio = { version = "1", features = ["full"] }
