// DTOs (Data Transfer Objects)
use serde::{Deserialize, Serialize};

/// Query parameters for the login challenge (`GET /api/user/auth`).
#[derive(Deserialize)]
pub struct ChallengeQuery {
    /// The Ethereum wallet address (e.g., 0x...)
    pub wallet_address: String,
}

/// Login challenge returned to the client.
#[derive(Serialize, Deserialize)]
pub struct ChallengeResponse {
    /// The unique nonce the user must sign
    pub nonce: String,
}

/// Signed login payload (`POST /api/user/auth`).
#[derive(Deserialize, Serialize)]
pub struct VerifySignaturRequest {
    /// The nonce that was signed.
    pub msg: String,
    /// The signature generated by signing the nonce
    pub signature: String,
}

/// Session payload returned after a successful login.
#[derive(Serialize, Deserialize)]
pub struct SessionResponse {
    /// JWT Bearer Token for authenticated requests
    pub token: String,
}
